const AUTH_SUCCESS = "AUTH_SUCCESS";
const AUTH_ERROR = "AUTH_ERROR";
const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";

const CONFIRMATION_ERROR = "CONFIRMATION_ERROR";
const CONFIRMATION_SUCCESS = "CONFIRMATION_SUCCESS";
const CONFIRMATION_EXPIRED = 'CONFIRMATION_EXPIRED'
const LOADING = "LOADING";
const ERROR = "ERROR";

const HIDE_ALERT = "HIDE_ALERT";
const LOGOUT_USER = "LOGOUT_USER";
const ADD_ARTICLE_SUCCESS = "ADD_ARTICLE_SUCCESS";

const GET_ARTICLES_SUCCESS = "GET_ARTICLES_SUCCESS";
const GET_ARTICLES_ERROR = "GET_ARTICLES_ERROR";
const TOGGLE_MENU = "TOGGLE_MENU"

export default {
  AUTH_SUCCESS,
  AUTH_ERROR,
  UPDATE_USER_SUCCESS,
  CONFIRMATION_ERROR,
  CONFIRMATION_SUCCESS,
  LOADING,
  ERROR,
  HIDE_ALERT,
  LOGOUT_USER,
  ADD_ARTICLE_SUCCESS,
  GET_ARTICLES_ERROR,
  GET_ARTICLES_SUCCESS,
  TOGGLE_MENU,
  CONFIRMATION_EXPIRED
};
